"use client";

import { useState } from "react";
import type { SqlPayload } from "../chat/Chat";
import { countLabel } from "@/lib/format";
import { seconds } from "./AnswerCard";

/**
 * "Show what data it pulled and how it arrived at an answer" - the
 * explainability requirement, made literal.
 *
 * The QuerySpec is shown as well as the SQL, because the spec is what the model
 * actually produced. The SQL was compiled from it deterministically, so the two
 * together trace the whole path from question to number.
 */
export default function ProvenancePanel({
  spec, sql, rowCount, elapsedMs, timing,
}: {
  spec?: unknown;
  sql?: SqlPayload;
  rowCount?: number;
  elapsedMs?: number;
  timing?: { total: number; extract: number; sql: number; narrate: number };
}) {
  const [open, setOpen] = useState(false);
  if (!spec && !sql) return null;

  return (
    <div className="prov">
      <button className="prov-toggle" onClick={() => setOpen((o) => !o)} aria-expanded={open}>
        <span className={`prov-caret${open ? " open" : ""}`}>▸</span>
        How I got this
        {rowCount !== undefined && (
          <span className="prov-summary">
            {countLabel(rowCount, "row")}
            {elapsedMs !== undefined ? ` · ${elapsedMs} ms` : ""}
          </span>
        )}
      </button>
      {open && (
        <div className="prov-body">
          {timing && timing.total > 0 && (
            <section>
              <h4>Where the time went</h4>
              {/* Worth its own section rather than a footnote. The database step
                  is routinely single-digit milliseconds while the whole answer
                  takes seconds - so the honest reading of a slow answer is
                  "the model was thinking", not "the query was slow". Without
                  this, the only timing on screen is the 9 ms one. */}
              <ul className="prov-timing">
                <li><span>Understanding the question</span><b>{seconds(timing.extract)}</b></li>
                <li><span>Querying the ledger</span><b>{seconds(timing.sql)}</b></li>
                <li><span>Writing and verifying the answer</span><b>{seconds(timing.narrate)}</b></li>
                <li className="prov-timing-total"><span>Total</span><b>{seconds(timing.total)}</b></li>
              </ul>
            </section>
          )}
          {spec ? (
            <section>
              <h4>1 · What the model produced</h4>
              <p className="prov-note">
                A typed query spec — not SQL. Every field is a closed set, so an
                invented dimension fails validation before it reaches the database.
              </p>
              <pre className="prov-code">{JSON.stringify(spec, null, 2)}</pre>
            </section>
          ) : null}
          {sql ? (
            <section>
              <h4>2 · The SQL compiled from it</h4>
              <p className="prov-note">
                Generated by Python from the spec above, never by the model.
                Values are bound parameters.
              </p>
              <pre className="prov-code">{sql.sql}</pre>
              {Object.keys(sql.params ?? {}).length > 0 && (
                <pre className="prov-code prov-params">
                  {JSON.stringify(sql.params, null, 2)}
                </pre>
              )}
            </section>
          ) : null}
        </div>
      )}
    </div>
  );
}
